// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package messages

import (
	"database/sql"
	"time"
)

type Message struct {
	ID       int64
	Message  string
	FromUser string
	ToUser   string
	Time     time.Time
	Status   sql.NullInt64
	Foreign  interface{}
}

type User struct {
	Uuid      string
	Email     string
	Username  interface{}
	Password  sql.NullString
	Createdat time.Time
}
