// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package messages

import (
	"context"
	"database/sql"
	"time"
)

const countUnreadUser = `-- name: CountUnreadUser :many
SELECT id, message, from_user, to_user, time, status, "foreign" FROM messages WHERE to_user = ? AND status = 0
`

func (q *Queries) CountUnreadUser(ctx context.Context, toUser string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, countUnreadUser, toUser)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.FromUser,
			&i.ToUser,
			&i.Time,
			&i.Status,
			&i.Foreign,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (
    message, from_user, to_user, time, status
) VALUES (
    ?, ?, ?, ?, ?
) RETURNING id, message, from_user, to_user, time, status, "foreign"
`

type CreateMessageParams struct {
	Message  string
	FromUser string
	ToUser   string
	Time     time.Time
	Status   sql.NullInt64
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRowContext(ctx, createMessage,
		arg.Message,
		arg.FromUser,
		arg.ToUser,
		arg.Time,
		arg.Status,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.FromUser,
		&i.ToUser,
		&i.Time,
		&i.Status,
		&i.Foreign,
	)
	return i, err
}

const getMessagesFromToUsers = `-- name: GetMessagesFromToUsers :many
SELECT
    m.id,
    m.message,
    m.from_user AS sender_id,
    sender.username AS sender_username,
    m.to_user AS receiver_id,
    receiver.username AS receiver_username,
    m.time
FROM messages m
JOIN users sender ON m.from_user = sender.uuid
JOIN users receiver ON m.to_user = receiver.uuid
WHERE (m.from_user = ? AND m.to_user = ?)
   OR (m.from_user = ? AND m.to_user = ?)
ORDER BY m.time DESC
LIMIT ? OFFSET ?
`

type GetMessagesFromToUsersParams struct {
	FromUser   string
	ToUser     string
	FromUser_2 string
	ToUser_2   string
	Limit      int64
	Offset     int64
}

type GetMessagesFromToUsersRow struct {
	ID               int64
	Message          string
	SenderID         string
	SenderUsername   interface{}
	ReceiverID       string
	ReceiverUsername interface{}
	Time             time.Time
}

func (q *Queries) GetMessagesFromToUsers(ctx context.Context, arg GetMessagesFromToUsersParams) ([]GetMessagesFromToUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesFromToUsers,
		arg.FromUser,
		arg.ToUser,
		arg.FromUser_2,
		arg.ToUser_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMessagesFromToUsersRow
	for rows.Next() {
		var i GetMessagesFromToUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Message,
			&i.SenderID,
			&i.SenderUsername,
			&i.ReceiverID,
			&i.ReceiverUsername,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
