// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package posts

import (
	"database/sql"
	"time"
)

type Post struct {
	ID         int64
	Title      string
	Categories string
	Content    string
	Author     string
	Time       time.Time
	ImagePath  sql.NullString
}

type User struct {
	Uuid      string
	Email     string
	Username  interface{}
	Password  sql.NullString
	Createdat time.Time
}
