// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package posts

import (
	"context"
	"database/sql"
	"time"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts(
    title, categories, content, author, time, image_path
)
VALUES(
    ?, ?, ?, ?, ?, ?

) RETURNING id, title, categories, content, author, time, image_path
`

type CreatePostParams struct {
	Title      string
	Categories string
	Content    string
	Author     string
	Time       time.Time
	ImagePath  sql.NullString
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.Title,
		arg.Categories,
		arg.Content,
		arg.Author,
		arg.Time,
		arg.ImagePath,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Categories,
		&i.Content,
		&i.Author,
		&i.Time,
		&i.ImagePath,
	)
	return i, err
}

const getPostByAuthor = `-- name: GetPostByAuthor :one
SELECT id, title, categories, content, author, time, image_path FROM posts 
WHERE author = ?
`

func (q *Queries) GetPostByAuthor(ctx context.Context, author string) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostByAuthor, author)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Categories,
		&i.Content,
		&i.Author,
		&i.Time,
		&i.ImagePath,
	)
	return i, err
}

const getPostById = `-- name: GetPostById :one
SELECT id, title, categories, content, author, time, image_path FROM posts 
WHERE id = ?
`

func (q *Queries) GetPostById(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPostById, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Categories,
		&i.Content,
		&i.Author,
		&i.Time,
		&i.ImagePath,
	)
	return i, err
}

const getPosts = `-- name: GetPosts :many
SELECT id, title, categories, content, author, time, image_path FROM posts ORDER BY time DESC LIMIT ? OFFSET ?
`

type GetPostsParams struct {
	Limit  int64
	Offset int64
}

func (q *Queries) GetPosts(ctx context.Context, arg GetPostsParams) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Categories,
			&i.Content,
			&i.Author,
			&i.Time,
			&i.ImagePath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const totalPosts = `-- name: TotalPosts :many
SELECT COUNT(*) FROM posts
`

func (q *Queries) TotalPosts(ctx context.Context) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, totalPosts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var count int64
		if err := rows.Scan(&count); err != nil {
			return nil, err
		}
		items = append(items, count)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePost = `-- name: UpdatePost :one
UPDATE posts SET title = ?, categories = ?, content = ? WHERE id = ? AND author = ? RETURNING id, title, categories, content, author, time, image_path
`

type UpdatePostParams struct {
	Title      string
	Categories string
	Content    string
	ID         int64
	Author     string
}

func (q *Queries) UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, updatePost,
		arg.Title,
		arg.Categories,
		arg.Content,
		arg.ID,
		arg.Author,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Categories,
		&i.Content,
		&i.Author,
		&i.Time,
		&i.ImagePath,
	)
	return i, err
}
