// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sessionDB

import (
	"time"
)

type Session struct {
	ID        int64
	Token     string
	Expiresat time.Time
	Userid    string
}
