// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sessionDB

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :one
INSERT INTO session (token, expiresAt, userId) VALUES (?, ?, ?) RETURNING id, token, expiresat, userid
`

type CreateSessionParams struct {
	Token     string
	Expiresat time.Time
	Userid    string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.Token, arg.Expiresat, arg.Userid)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Expiresat,
		&i.Userid,
	)
	return i, err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM session WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionUser = `-- name: DeleteSessionUser :exec
DELETE FROM session WHERE userId = ?
`

func (q *Queries) DeleteSessionUser(ctx context.Context, userid string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionUser, userid)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, token, expiresat, userid FROM session WHERE id = ? LIMIT 1
`

func (q *Queries) GetSessionByID(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByID, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Expiresat,
		&i.Userid,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT id, token, expiresat, userid FROM session WHERE token = ? LIMIT 1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Expiresat,
		&i.Userid,
	)
	return i, err
}

const getSessionByUserID = `-- name: GetSessionByUserID :one
SELECT id, token, expiresat, userid FROM session WHERE userId = ? LIMIT 1
`

func (q *Queries) GetSessionByUserID(ctx context.Context, userid string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSessionByUserID, userid)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Expiresat,
		&i.Userid,
	)
	return i, err
}

const sessionExistsDB = `-- name: SessionExistsDB :one
SELECT id, token, expiresat, userid FROM session WHERE userId = ? LIMIT 1
`

func (q *Queries) SessionExistsDB(ctx context.Context, userid string) (Session, error) {
	row := q.db.QueryRowContext(ctx, sessionExistsDB, userid)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.Expiresat,
		&i.Userid,
	)
	return i, err
}
