// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package comments

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID      int64
	Content interface{}
	Author  string
	PostID  interface{}
	Time    time.Time
}

type User struct {
	Uuid      string
	Email     string
	Username  interface{}
	Password  sql.NullString
	Createdat time.Time
}
