// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package comments

import (
	"time"
)

type Comment struct {
	ID      int64
	Content interface{}
	Author  string
	PostID  interface{}
	Time    time.Time
}
