// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package comments

import (
	"context"
	"time"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments(
    content, author, post_id, time
)
VALUES(
    ?, ?, ?, ?
) RETURNING id, content, author, post_id, time
`

type CreateCommentParams struct {
	Content interface{}
	Author  string
	PostID  interface{}
	Time    time.Time
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.Content,
		arg.Author,
		arg.PostID,
		arg.Time,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Author,
		&i.PostID,
		&i.Time,
	)
	return i, err
}

const getCommentByAuthor = `-- name: GetCommentByAuthor :one
SELECT id, content, author, post_id, time FROM comments
WHERE author = ?
`

func (q *Queries) GetCommentByAuthor(ctx context.Context, author string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentByAuthor, author)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Author,
		&i.PostID,
		&i.Time,
	)
	return i, err
}

const getCommentById = `-- name: GetCommentById :one
SELECT id, content, author, post_id, time FROM comments
WHERE id = ?
`

func (q *Queries) GetCommentById(ctx context.Context, id int64) (Comment, error) {
	row := q.db.QueryRowContext(ctx, getCommentById, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Author,
		&i.PostID,
		&i.Time,
	)
	return i, err
}

const getCommentsByPostId = `-- name: GetCommentsByPostId :many
SELECT id, content, author, post_id, time FROM comments WHERE post_id = ?
`

func (q *Queries) GetCommentsByPostId(ctx context.Context, postID interface{}) ([]Comment, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByPostId, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Comment
	for rows.Next() {
		var i Comment
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Author,
			&i.PostID,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCommentsWithAuthorUsername = `-- name: GetCommentsWithAuthorUsername :many
SELECT
    comments.id,
    comments.content,
    comments.author,
    comments.content,
    comments.post_id,
    users.username AS author_username,
    comments.time
FROM comments
JOIN users ON comments.author = users.uuid
WHERE comments.post_id = ?
ORDER BY comments.time DESC LIMIT ? OFFSET ?
`

type GetCommentsWithAuthorUsernameParams struct {
	PostID interface{}
	Limit  int64
	Offset int64
}

type GetCommentsWithAuthorUsernameRow struct {
	ID             int64
	Content        interface{}
	Author         string
	Content_2      interface{}
	PostID         interface{}
	AuthorUsername interface{}
	Time           time.Time
}

func (q *Queries) GetCommentsWithAuthorUsername(ctx context.Context, arg GetCommentsWithAuthorUsernameParams) ([]GetCommentsWithAuthorUsernameRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsWithAuthorUsername, arg.PostID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsWithAuthorUsernameRow
	for rows.Next() {
		var i GetCommentsWithAuthorUsernameRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Author,
			&i.Content_2,
			&i.PostID,
			&i.AuthorUsername,
			&i.Time,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments SET content = ? WHERE id = ? AND author = ? RETURNING id, content, author, post_id, time
`

type UpdateCommentParams struct {
	Content interface{}
	ID      int64
	Author  string
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.Content, arg.ID, arg.Author)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.Author,
		&i.PostID,
		&i.Time,
	)
	return i, err
}
