// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package users

import (
	"database/sql"
	"time"
)

type User struct {
	Uuid      string
	Email     string
	Username  interface{}
	Password  sql.NullString
	Auth      string
	Picture   sql.NullString
	Createdat time.Time
}
