// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package users

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    uuid, email, username, password, createdAt
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING uuid, email, username, password, createdat
`

type CreateUserParams struct {
	Uuid      string
	Email     string
	Username  interface{}
	Password  sql.NullString
	Createdat time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Uuid,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Createdat,
	)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT uuid, email, username, password, createdat FROM users
WHERE uuid = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, email, username, password, createdat FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT uuid, email, username, password, createdat FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username interface{}) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
set username = ?, email = ?
WHERE uuid = ?
RETURNING uuid, email, username, password, createdat
`

type UpdateUserParams struct {
	Username interface{}
	Email    string
	Uuid     string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Username, arg.Email, arg.Uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}
