// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package users

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users(
    uuid, email, username, password, createdAt
) VALUES (
    ?, ?, ?, ?, ?
)
RETURNING uuid, email, username, password, createdat
`

type CreateUserParams struct {
	Uuid      string
	Email     string
	Username  interface{}
	Password  sql.NullString
	Createdat time.Time
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Uuid,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Createdat,
	)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const getLatestMessages = `-- name: GetLatestMessages :many
SELECT
    u.uuid AS partner_id,
    u.username AS partner_username,
    MAX(m.time) AS last_message_time
FROM users u
JOIN messages m
  ON (u.uuid = m.from_user AND m.to_user = ?)
  OR (u.uuid = m.to_user AND m.from_user = ?)
WHERE u.uuid != ?
GROUP BY u.uuid, u.username

UNION ALL

SELECT
    u.uuid AS partner_id,
    u.username AS partner_username,
    NULL AS last_message_time
FROM users u
WHERE u.uuid != ?
  AND u.uuid NOT IN (
      SELECT
          CASE
              WHEN m.from_user = ? THEN m.to_user
              ELSE m.from_user
          END AS partner_id
      FROM messages m
      WHERE m.from_user = ? OR m.to_user = ?
  )
ORDER BY
    last_message_time DESC,
    partner_username ASC
`

type GetLatestMessagesParams struct {
	ToUser     string
	FromUser   string
	Uuid       string
	Uuid_2     string
	FromUser_2 string
	FromUser_3 string
	ToUser_2   string
}

type GetLatestMessagesRow struct {
	PartnerID       string
	PartnerUsername interface{}
	LastMessageTime interface{}
}

func (q *Queries) GetLatestMessages(ctx context.Context, arg GetLatestMessagesParams) ([]GetLatestMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, getLatestMessages,
		arg.ToUser,
		arg.FromUser,
		arg.Uuid,
		arg.Uuid_2,
		arg.FromUser_2,
		arg.FromUser_3,
		arg.ToUser_2,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLatestMessagesRow
	for rows.Next() {
		var i GetLatestMessagesRow
		if err := rows.Scan(&i.PartnerID, &i.PartnerUsername, &i.LastMessageTime); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT uuid, email, username, password, createdat FROM users
WHERE uuid = ? LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT uuid, email, username, password, createdat FROM users WHERE email = ? LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT uuid, email, username, password, createdat FROM users
WHERE username = ? LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username interface{}) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const getUserOr = `-- name: GetUserOr :one
SELECT uuid, email, username, password, createdat
FROM users
WHERE username = ? OR email = ?
LIMIT 1
`

type GetUserOrParams struct {
	Username interface{}
	Email    string
}

func (q *Queries) GetUserOr(ctx context.Context, arg GetUserOrParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserOr, arg.Username, arg.Email)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
set username = ?, email = ?
WHERE uuid = ?
RETURNING uuid, email, username, password, createdat
`

type UpdateUserParams struct {
	Username interface{}
	Email    string
	Uuid     string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser, arg.Username, arg.Email, arg.Uuid)
	var i User
	err := row.Scan(
		&i.Uuid,
		&i.Email,
		&i.Username,
		&i.Password,
		&i.Createdat,
	)
	return i, err
}
