CREATE TABLE users (
uuid TEXT PRIMARY KEY,
email VARCHAR(255) NOT NULL UNIQUE,
username LONGTEXT NOT NULL UNIQUE,
password VARCHAR(255),
auth VARCHAR(255) NOT NULL,
picture VARCHAR(255),
createdAt DATETIME NOT NULL
);